import "./globals.css";
import type { Metadata } from "next";
import { Sora, Spline_Sans } from "next/font/google";
import Providers from "@/providers/provider-ui";
import { Navbar } from "@/components/navbar";
import { ScrollArea } from "@/components/ui/scroll-area";

const sora = Sora({
  subsets: ["latin"],
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800']
});

const splineSans = Spline_Sans({
  subsets: ["latin"],
  variable: '--font-spline-sans',
  weight: ['300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${sora.variable} ${splineSans.variable}`}>
      <head />
      <body
        className={`bg-[url('/site-bg.svg')] bg-cover relative`}
      >
        <Providers>
          <ScrollArea className="h-screen w-screen z-[100]">
            <Navbar />
            <main className="px-[146px]">{children}</main>
          </ScrollArea>
        </Providers>
      </body>
    </html>
  );
}
