import "./globals.css";
import type { Metadata } from "next";
import { Sora, Spline_Sans } from "next/font/google";
import Providers from "@/providers/provider-ui";
import { Navbar } from "@/components/navbar";
import { ScrollArea } from "@/components/ui/scroll-area";
import ToasterProvider from "@/providers/toaster-provider";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const splineSans = Spline_Sans({
  subsets: ["latin"],
  variable: "--font-spline-sans",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${sora.variable} ${splineSans.variable}`}>
      <head />
      <body className={`bg-[url('/site-bg.svg')] bg-cover relative  min-h-fit scroll-smooth`}>
        <ToasterProvider />
        <ScrollArea className="h-screen w-screen">
          <Providers>
            <Navbar />
            <main className="px-[20px] phone:px-[40px] sm:px-[80px] lg:px-[146px] relative">{children}</main>
          </Providers>
        </ScrollArea>
      </body>
    </html>
  );
}
